apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["while true; do date >> /exchange/shared.txt; sleep 5; done;"]
        volumeMounts:
        - name: exchange-vol
          mountPath: /exchange
      - name: multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo '----- multitool read file -----'; cat /exchange/shared.txt || true; sleep 5; done;"]
        volumeMounts:
        - name: exchange-vol
          mountPath: /exchange
      volumes:
      - name: exchange-vol
        emptyDir: {}